#!/bin/bash

PLUGIN_DIR="$CONFIG_DIR/plugins"
source "$CONFIG_DIR/colors.sh"
source "$CONFIG_DIR/icons.sh"

sketchybar --bar position=top height=40 blur_radius=30 color=$BASE

default=(
  padding_left=5
  padding_right=5
  icon.font="CaskaydiaCove Nerd Font:Bold:17.0"
  label.font="CaskaydiaCove Nerd Font:Bold:14.0"
  icon.color=0xffffffff
  label.color=0xffffffff
  icon.padding_left=4
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=4
)
sketchybar --default "${default[@]}"

for did in $(yabai -m query --displays | jq '.[].index'); do
  local_idx=1

  for sid in $(yabai -m query --spaces --display "$did" | jq '.[].index'); do
    space=(
      space="$sid"
      icon="$local_idx"
      icon.padding_left=7
      icon.padding_right=7
      background.color=0x40ffffff
      background.corner_radius=5
      background.height=25
      label.drawing=off
      script="$PLUGIN_DIR/space.sh"
      click_script="yabai -m space --focus $sid"
    )
    sketchybar --add space space."$sid" left --set space."$sid" "${space[@]}"
    local_idx=$((local_idx + 1))
  done
done

# Left

sketchybar --add item chevron left \
  --set chevron label.drawing=off \
  --add item front_app left \
  --set front_app icon.drawing=off script="$PLUGIN_DIR/front_app.sh" \
  --subscribe front_app front_app_switched

# Center

sketchybar --add item clock center \
  --set clock update_freq=10 script="$PLUGIN_DIR/clock.sh" \
  --add item volume right \
  --set volume script="$PLUGIN_DIR/volume.sh" \
  --subscribe volume volume_change \
  --add item battery right \
  --set battery update_freq=60 script="$PLUGIN_DIR/battery.sh" \
  --subscribe battery system_woke power_source_change

# Right

cpu=(
  icon="$CPU"
  update_freq=3
  script="$PLUGIN_DIR/stats/cpu.sh"
)

sketchybar --add item cpu right \
  --set cpu "${cpu[@]}"

memory=(
  icon="$MEMORY"
  update_freq=5
  script="$PLUGIN_DIR/stats/ram.sh"
)

sketchybar --add item memory right \
  --set memory "${memory[@]}"

disk=(
  icon="$DISK"
  update_freq=60
  script="$PLUGIN_DIR/stats/disk.sh"
)

sketchybar --add item disk right \
  --set disk "${disk[@]}"

network_down=(
  icon="$NETWORK_DOWN"
  icon.color=0xffffffff
  update_freq=1
)

network_up=(
  icon="$NETWORK_UP"
  update_freq=1
  script="$PLUGIN_DIR/stats/network.sh"
)

sketchybar --add item network.down right \
  --set network.down "${network_down[@]}" \
  --add item network.up right \
  --set network.up "${network_up[@]}"

sketchybar --update
