#!/bin/bash

PLUGIN_DIR="$CONFIG_DIR/plugins"
source "$CONFIG_DIR/colors.sh"
source "$CONFIG_DIR/icons.sh"

default=(
  padding_left=4
  padding_right=4
  icon.font="CaskaydiaCove Nerd Font:Bold:17.0"
  label.font="CaskaydiaCove Nerd Font:Bold:14.0"
  icon.color="$TEXT"
  label.color="$TEXT"
  icon.padding_left=10
  icon.padding_right=10
  label.padding_left=10
  label.padding_right=10
)

default_section=(
  background.color="$SURFACE"
  background.border_color="$OVERLAY"
  background.border_width=2
  background.corner_radius=8
  background.height=35
)

default_label=(
  label.padding_left=0
  label.padding_right=4
  icon.padding_right=4
  icon.padding_left=4
)

"$BAR_NAME" --default "${default[@]}"

source "$CONFIG_DIR/bars/${BAR_NAME}.sh"

"$BAR_NAME" --update
