#!/bin/bash

PLUGIN_DIR="$CONFIG_DIR/plugins"
source "$CONFIG_DIR/colors.sh"
source "$CONFIG_DIR/icons.sh"

sketchybar --bar position=top height=45 color=$BASE

default=(
  padding_left=5
  padding_right=5
  icon.font="CaskaydiaCove Nerd Font:Bold:17.0"
  label.font="CaskaydiaCove Nerd Font:Bold:14.0"
  icon.color=0xffffffff
  label.color=0xffffffff
  icon.padding_left=4
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=4
)
sketchybar --default "${default[@]}"

sketchybar --add event yabai_updated

sketchybar --add item spaces_trigger left \
  --set spaces_trigger drawing=off \
    script="$PLUGIN_DIR/spaces.sh" \
  --subscribe spaces_trigger yabai_updated

source "$PLUGIN_DIR/spaces.sh"

# Left

sketchybar --add item chevron left \
  --set chevron label.drawing=off \
  --add item front_app left \
  --set front_app icon.drawing=off script="$PLUGIN_DIR/front_app.sh" \
  --subscribe front_app front_app_switched

sketchybar --add item "clock.1" left \
  --set "clock.1" update_freq=10 script="$PLUGIN_DIR/clock.sh" display="1"

# Center

sketchybar --add item volume right \
  --set volume script="$PLUGIN_DIR/volume.sh" \
  --subscribe volume volume_change \
  --add item battery right \
  --set battery update_freq=60 script="$PLUGIN_DIR/battery.sh" \
  --subscribe battery system_woke power_source_change

for did in $(yabai -m query --displays | jq '.[].index | select(. != 1)'); do
  sketchybar --add item "clock.$did" center \
    --set "clock.$did" update_freq=10 script="$PLUGIN_DIR/clock.sh" display="$did"
done

# Right

cpu=(
  icon="$CPU"
  update_freq=3
  script="$PLUGIN_DIR/stats/cpu.sh"
)

sketchybar --add item cpu right \
  --set cpu "${cpu[@]}"

memory=(
  icon="$MEMORY"
  update_freq=5
  script="$PLUGIN_DIR/stats/ram.sh"
)

sketchybar --add item memory right \
  --set memory "${memory[@]}"

disk=(
  icon="$DISK"
  update_freq=60
  script="$PLUGIN_DIR/stats/disk.sh"
)

sketchybar --add item disk right \
  --set disk "${disk[@]}"

network_down=(
  icon="$NETWORK_DOWN"
  icon.color=0xffffffff
  update_freq=1
)

network_up=(
  icon="$NETWORK_UP"
  update_freq=1
  script="$PLUGIN_DIR/stats/network.sh"
)

sketchybar --add item network.down right \
  --set network.down "${network_down[@]}" \
  --add item network.up right \
  --set network.up "${network_up[@]}"

sketchybar --update
