#!/bin/sh

layout_generator=rivertile

riverctl map normal Super Return spawn "uwsm app -- wezterm"
riverctl map normal Alt+Shift F spawn "killall .firefox-wrapped || uwsm app -- firefox"
riverctl map normal Alt+Shift+Control F spawn "killall .firefox-wrapped || uwsm app -- firefox-vpn"
riverctl map normal Super T spawn 'uwsm app -- rofi -show drun -drun-exclude-categories "Game"'
riverctl map normal Super N spawn "uwsm app -- $HOME/nixos-config/home-manager/rofi/search-nix-pkgs.sh"
riverctl map normal Super S spawn "uwsm app -- grim -g \"\$(slurp)\" - | wl-copy"

riverctl map normal Alt+Shift Q close
riverctl map normal Control+Shift E exit

riverctl input pointer-1133-45082-MX_Anywhere_2S_Mouse middle-emulation enabled

riverctl map normal Control+Shift+Super R spawn 'killall -SIGUSR2 .waybar-wrapped || (uwsm app -- waybar & dunstify "Reloaded waybar.")'

riverctl map normal Control+Shift K focus-view up
riverctl map normal Control+Shift J focus-view down
riverctl map normal Control+Shift H focus-view left
riverctl map normal Control+Shift L focus-view right

riverctl map normal Control+Shift bracketright swap next
riverctl map normal Control+Shift bracketleft swap previous

riverctl map normal Control+Shift+Alt K swap up
riverctl map normal Control+Shift+Alt J swap down
riverctl map normal Control+Shift+Alt H swap left
riverctl map normal Control+Shift+Alt L swap right

riverctl map normal Control Period focus-output next
riverctl map normal Control Comma focus-output previous
riverctl map normal Control+Shift Period send-to-output next
riverctl map normal Control+Shift Comma send-to-output previous

riverctl map normal Control Return zoom
riverctl map normal Control+Shift MINUS send-layout-cmd "$layout_generator" "main-ratio -0.05"
riverctl map normal Control+Shift EQUAL send-layout-cmd "$layout_generator" "main-ratio +0.05"

riverctl map normal Control+Alt H move left 100
riverctl map normal Control+Alt J move down 100
riverctl map normal Control+Alt K move up 100
riverctl map normal Control+Alt L move right 100

riverctl map normal Super+Alt+Control H snap left
riverctl map normal Super+Alt+Control J snap down
riverctl map normal Super+Alt+Control K snap up
riverctl map normal Super+Alt+Control L snap right

riverctl map normal Super+Alt+Shift H resize horizontal 100
riverctl map normal Super+Alt+Shift J resize vertical 100
riverctl map normal Super+Alt+Shift K resize vertical 100
riverctl map normal Super+Alt+Shift L resize horizontal -100

riverctl map-pointer normal Super BTN_LEFT move-view
riverctl map-pointer normal Super BTN_RIGHT resize-view
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

# --- TAGS (1-9) ---
for i in $(seq 1 9); do
    tags=$((1 << (i - 1)))
    riverctl map normal Super "$i" set-focused-tags $tags
    riverctl map normal Super+Shift "$i" set-view-tags $tags
    riverctl map normal Super+Control "$i" toggle-focused-tags $tags
    riverctl map normal Super+Shift+Control "$i" toggle-view-tags $tags
done

bluetooth_tag=$((1 << 9))
riverctl rule-add -title "Bluetooth Devices" tags $bluetooth_tag
riverctl map normal Super B set-focused-tags $bluetooth_tag

discord_tag=$((1 << 8))
riverctl rule-add -title "Discord" tags $discord_tag
riverctl map normal Super D set-focused-tags $discord_tag

games_tag=$((1 << 7))
riverctl rule-add -app-id "*steam*" tags $games_tag
riverctl map normal Super G set-focused-tags $games_tag

# All tags/Global
all_tags=$(((1 << 9) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

riverctl map normal Super Space toggle-float
riverctl map normal Super F toggle-fullscreen

# Layout Orientation
riverctl map normal Super Up send-layout-cmd "$layout_generator" "main-location top"
riverctl map normal Super Right send-layout-cmd "$layout_generator" "main-location right"
riverctl map normal Super Down send-layout-cmd "$layout_generator" "main-location bottom"
riverctl map normal Super Left send-layout-cmd "$layout_generator" "main-location left"

# Passthrough Mode
riverctl declare-mode passthrough
riverctl map normal Super F11 enter-mode passthrough
riverctl map passthrough Super F11 enter-mode normal

for mode in normal locked; do
    riverctl map $mode None XF86Eject spawn 'eject -T'
    riverctl map $mode None XF86AudioRaiseVolume spawn 'pamixer -i 5'
    riverctl map $mode None XF86AudioLowerVolume spawn 'pamixer -d 5'
    riverctl map $mode None XF86AudioMute spawn 'pamixer --toggle-mute'
    riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPlay spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPrev spawn 'playerctl previous'
    riverctl map $mode None XF86AudioNext spawn 'playerctl next'
    riverctl map $mode None XF86MonBrightnessUp spawn 'brightnessctl set +5%'
    riverctl map $mode None XF86MonBrightnessDown spawn 'brightnessctl set 5%-'
done

riverctl background-color 0x002b36
riverctl border-color-focused 0x93a1a1
riverctl border-color-unfocused 0x586e75
riverctl border-width 3
riverctl set-repeat 50 300

riverctl rule-add -app-id 'float*' -title 'foo' float
riverctl rule-add -app-id "bar" csd

riverctl default-layout "$layout_generator"
$layout_generator -view-padding 6 -outer-padding 6 &

# It makes sure WAYLAND_DISPLAY is shared and unblocks graphical-session.target.
uwsm finalize

# Using 'uwsm app --' ensures these stay alive correctly and die on logout.
uwsm app -- wezterm &
uwsm app -- blueman-applet &
uwsm app -- blueman-manager &
uwsm app -- discord.desktop &
uwsm app -- steam -silent &
uwsm app -- lxqt-policykit-agent &

# Clipboard management
uwsm app -- wl-paste --primary --watch sh -c "echo \$(cat) | cliphist -db-path $HOME/.cache/cliphist/primary-db store" &
uwsm app -- wl-paste --watch sh -c "echo \$(cat) | cliphist -db-path $HOME/.cache/cliphist/system-db store" &
