-- [nfnl] fnl/mappings/init.fnl
local km_set = vim.keymap.set
km_set({"n", "v"}, "<Space>", "<Nop>", {silent = true})
km_set("n", "k", "v:count == 0 ? 'gk' : 'k'", {expr = true, silent = true})
km_set("n", "j", "v:count == 0 ? 'gj' : 'j'", {expr = true, silent = true})
km_set("n", "<A-Down>", ":m .+1<CR>==", {desc = "Move line down", silent = true})
km_set("n", "<A-Up>", ":m .-2<CR>==", {desc = "Move line up", silent = true})
km_set("i", "<A-Down>", "<Esc>:m .+1<CR>==gi", {desc = "Move line down", silent = true})
km_set("i", "<A-Up>", "<Esc>:m .-2<CR>==gi", {desc = "Move line up", silent = true})
km_set("v", "<A-Down>", ":m '>+1<CR>gv=gv", {desc = "Move line down", silent = true})
km_set("v", "<A-Up>", ":m '<-2<CR>gv=gv", {desc = "Move line up", silent = true})
km_set("n", "<leader>o", "o<Esc>k", {silent = true})
km_set("n", "<leader>O", "O<Esc>j", {silent = true})
km_set({"n", "v"}, "<leader>dd", "\"_dd<Esc>", {silent = true})
km_set({"v"}, "<leader>d", "\"_d<Esc>", {silent = true})
km_set({"n"}, "<leader>x", "\"_x<Esc>", {silent = true})
km_set("n", "<leader>xa", ":wa | qa<cr>", {desc = "Write and close all buffers while terminal open", silent = true})
km_set("n", "<leader>w", ":w<cr>", {desc = "[W]rite", silent = true})
km_set("n", "<leader>wa", ":wa<cr>", {desc = "[W]rite [A]ll", silent = true})
km_set("n", "<C-a>", ":normal gg0vG$<cr>", {desc = "Select all text"})
local function _1_()
  return vim.diagnostic.jump({count = 1, float = true})
end
km_set("n", "[d", _1_, {desc = "Go to previous diagnostic message"})
local function _2_()
  return vim.diagnostic.jump({count = -1, float = true})
end
km_set("n", "]d", _2_, {desc = "Go to next diagnostic message"})
km_set("n", "<leader>d", vim.diagnostic.open_float, {desc = "Open floating diagnostic message"})
km_set("n", "<leader>c", ":let @+=expand('%')<cr>", {desc = "[C]opy current buffer name", silent = true})
km_set("i", "<C-L>", "<Plug>(copilot-accept-word)")
km_set("n", "<leader>gs", ":Git<CR>")
km_set("n", "<leader>gd", ":Gdiffsplit<CR>")
km_set("n", "<leader>gc", ":Git commit<CR>")
km_set("n", "<leader>gb", ":Git blame<CR>")
km_set("n", "<leader>gm", ":Git mergetool<CR>")
vim.opt.diffopt:append("algorithm:patience")
return vim.opt.diffopt:append("indent-heuristic")
