{
  config,
  lib,
  pkgs,
  pkgs-unstable,
  osConfig,
  ...
}:
let
  sketchybarBottom = pkgs.callPackage ../pkgs/sketchybar-bottom.nix { inherit pkgs-unstable; };

  colorsScript = pkgs.writeShellScript "colors.sh" ''
    # Generated by Nix from the active Stylix base16 scheme. Do not edit.
    # See home-manager/colors.nix.
    ${lib.concatStringsSep "\n" (
      lib.mapAttrsToList (n: v: "export ${n}=${v}") (lib.filterAttrs (_: lib.isString) osConfig.palette)
    )}
  '';

  mkSymLink = config.lib.file.mkOutOfStoreSymlink;

  sketchybarInstances = [
    "sketchybar"
    "sketchybar-bottom"
  ];

  mkSketchybarLinks =
    instance:
    (lib.mapAttrs' (
      file: _:
      lib.nameValuePair "${instance}/${file}" {
        source = mkSymLink "${config.dotfilesPath}/sketchybar/${file}";
      }
    ) (builtins.readDir ./dotfiles/sketchybar))
    // {
      "${instance}/colors.sh".source = colorsScript;
    };

  sketchybarLinks = lib.foldl' (
    acc: instance: acc // mkSketchybarLinks instance
  ) { } sketchybarInstances;

  # Symlink farm at $root/.workspaces/<TICKET>: every repo resolves to its
  # ticket worktree (from a New-WorktreeSession session dir) or, failing that,
  # the main clone. Prints the workspace path last: nvim "$(sw-workspace X | tail -1)"
  swWorkspace = pkgs.writeShellScriptBin "sw-workspace" ''
    set -euo pipefail

    root="''${WORKTREE_SOURCE_ROOT:-$HOME/smartwyre}"

    if [ $# -ne 1 ]; then
      echo "usage: sw-workspace <TICKET> | list" >&2
      exit 1
    fi
    arg=$1

    # Session dirs are detected structurally: no top-level .git and at least
    # one immediate subdir whose .git is a file (= a worktree). Primary clones
    # have a .git directory; a stray worktree at root has a top-level .git file.
    is_session_dir() {
      [ -e "$1/.git" ] && return 1
      local wt
      for wt in "$1"/*/; do
        [ -f "''${wt}.git" ] && return 0
      done
      return 1
    }

    if [ "$arg" = list ]; then
      for d in "$root"/*/; do
        is_session_dir "$d" || continue
        repos=()
        for s in "$d"*/; do
          [ -e "''${s}.git" ] && repos+=("$(basename "$s")")
        done
        printf '%s: %s\n' "$(basename "$d")" "''${repos[*]}"
      done
      exit 0
    fi

    if is_session_dir "$root/$arg"; then
      # Exact session-dir name given
      session="$root/$arg"
      if [[ $arg =~ ^([A-Za-z]+-[0-9]+) ]]; then
        ticket=$(tr '[:lower:]' '[:upper:]' <<<"''${BASH_REMATCH[1]}")
      else
        echo "sw-workspace: cannot derive a ticket from '$arg'" >&2
        exit 1
      fi
    else
      ticket=$(tr '[:lower:]' '[:upper:]' <<<"$arg")
      candidates=()
      for d in "$root/$ticket"-*/; do
        [ -d "$d" ] || continue
        is_session_dir "$d" && candidates+=("''${d%/}")
      done
      if [ "''${#candidates[@]}" -eq 0 ]; then
        echo "sw-workspace: no session for $ticket under $root" >&2
        exit 1
      elif [ "''${#candidates[@]}" -gt 1 ]; then
        echo "sw-workspace: multiple sessions for $ticket:" >&2
        printf '  %s\n' "''${candidates[@]##*/}" >&2
        echo "re-run with the full session dir name" >&2
        exit 1
      fi
      session=''${candidates[0]}
    fi

    ws="$root/.workspaces/$ticket"
    mkdir -p "$ws"
    find "$ws" -maxdepth 1 -type l -delete

    for d in "$session"/*/; do
      [ -e "''${d}.git" ] || continue
      name=$(basename "$d")
      ln -sfn "''${d%/}" "$ws/$name"
      printf '%s -> %s (worktree)\n' "$name" "''${d%/}"
    done

    for d in "$root"/*/; do
      [ -d "''${d}.git" ] || continue
      name=$(basename "$d")
      [ -e "$ws/$name" ] && continue
      ln -sfn "''${d%/}" "$ws/$name"
      printf '%s -> %s (main)\n' "$name" "''${d%/}"
    done

    printf '%s\n' "$ws"
  '';
in
{
  imports = [
    ./modules/firefox.nix
    ./options/work.nix
    ./shared.nix
  ];

  targets.darwin.copyApps.enable = true;
  targets.darwin.linkApps.enable = false;

  home.homeDirectory = "/Users/andybolton";

  xdg.configFile = sketchybarLinks // {
    "skhd/home-manager.skhdrc".source = mkSymLink "${config.dotfilesPath}/skhd/home-manager.skhdrc";
  };

  home.file.".hammerspoon/init.lua".source = mkSymLink "${config.dotfilesPath}/hammerspoon/init.lua";

  home.packages = with pkgs; [
    _1password-cli
    _1password-gui
    (azure-cli.withExtensions [
      azure-cli-extensions.azure-devops
      azure-cli-extensions.durabletask
      azure-cli-extensions.resource-graph
    ])
    (pkgs.writeShellScriptBin "jetkvm-kiosk" ''
      set -e

      mkdir -p "${config.home.homeDirectory}/vms"
      # --out-link roots the image against GC; the overlay's backing file lives
      # in the store, so without a root a GC would corrupt the overlay.
      nix build ${config.repoPath}#nixosConfigurations.jetkvm-kiosk.config.system.build.images.qemu-efi \
        --out-link "${config.home.homeDirectory}/vms/jetkvm-kiosk-base"
      base=$(echo "$(readlink -f "${config.home.homeDirectory}/vms/jetkvm-kiosk-base")"/*.qcow2)
      overlay="${config.home.homeDirectory}/vms/jetkvm-kiosk-overlay.qcow2"
      cur=$(${pkgs.qemu}/bin/qemu-img info --output=json "$overlay" 2>/dev/null | ${pkgs.jq}/bin/jq -r '."backing-filename" // empty')

      if [ "$cur" != "$base" ]; then
        echo "New base image, recreating overlay..."
        ${pkgs.qemu}/bin/qemu-img create -f qcow2 -F qcow2 -b "$base" "$overlay"
      fi

      exec ${pkgs.qemu}/bin/qemu-system-aarch64 \
        -machine virt \
        -accel hvf \
        -cpu host \
        -m 2G \
        -smp 2 \
        -nic user,model=virtio-net-pci \
        -drive file="$overlay",if=virtio \
        -drive if=pflash,format=raw,readonly=on,file=${pkgs.qemu}/share/qemu/edk2-aarch64-code.fd \
        -device virtio-gpu-pci \
        -display cocoa,full-screen=on,full-grab=on \
        -device qemu-xhci \
        -device usb-kbd \
        -device usb-tablet \
        "$@"
    '')
    desktoppr
    gatherv2
    jira-cli-go
    maccy
    moonlight-qt
    pngpaste
    powershell
    powershell-editor-services
    sketchybarBottom
    swWorkspace # per-ticket worktree symlink farm for nvim
  ];

  # Global context loaded into every Claude Code session (~/.claude/CLAUDE.md).
  # Plain markdown; escape ''${ as '''${ and '' as ''' if you add code samples.
  programs.claude-code.context = ''
    # Global instructions

    - Be concise and direct — skip preamble and flattery. Applies to chat, Jira comments, and PR descriptions.
    - State each fact once. Don't restate context or explain the same thing two ways.
    - Don't comment self-evident code; reserve comments for non-obvious logic, and keep any explanatory context short.
    - Length must be earned by complexity or risk, not padding. When unsure, cut.
    - PR descriptions: routine change → self-contained body. Risky or multi-step change → short body (what / why + links), with the runbook (ordered steps, timings, rollback) living in a Confluence document and linked from the PR.
    - Make minimal changes. If something can be written better, bring it up but don't implement it immediately.

    ## Epistemics
    - Label platform-capability claims by evidence class: [tested this session],
      [doc + URL fetched this session], [inferred], [training memory]. Never
      deliver [inferred] in the same register as [tested].
    - "X is impossible / the only way is Y" requires, in the same message, a
      current-doc citation or a concrete runtime test that would falsify it.
      Otherwise phrase it as a hypothesis.
    - An unverified caveat is a to-do, not a disclaimer: resolve it before
      building on the claim, or state "the following builds on unverified
      assumption X".
    - For fast-moving platforms (Foundry, Claude API, GitHub), fetch the current
      doc before answering capability questions, even when confident. Source
      precedence: runtime test > current docs > API specs > Q&A/blogs > memory.
    - Scope claims exactly: "Sonnet 5.x" ≠ "Claude"; "the UI accepts it" ≠ "the
      runtime supports it"; "not documented" ≠ "not supported".
    - When corrected, also hunt down sibling claims sharing the broken premise —
      don't just patch the one that got caught.
  '';

  programs.claude-code.mcpServers = {
    atlassian = {
      type = "sse";
      url = "https://mcp.atlassian.com/v1/sse";
    };

    azure = {
      type = "stdio";
      command = "npx";
      args = [
        "-y"
        "@azure/mcp@latest"
        "server"
        "start"
      ];
    };

    azure-devops = {
      type = "stdio";
      command = "npx";
      args = [
        "-y"
        "@azure-devops/mcp"
        "smartwyre"
      ];
    };

    terraform = {
      type = "stdio";
      command = "npx";
      args = [
        "-y"
        "terraform-mcp-server"
      ];
    };
  };

  # Work claude sessions all launch from ~/smartwyre so sessions and
  # auto-memory share one project bucket (resume + recall work everywhere).
  programs.fish.functions.swc = {
    description = "claude from ~/smartwyre (shared work session/memory bucket)";
    body = ''
      pushd ~/smartwyre
      claude $argv
      popd
    '';
  };

  home.sessionPath = [
    "${config.home.homeDirectory}/Applications/Home Manager Apps/WezTerm.app"
  ];

  home.sessionVariables = {
    BROWSER = "${pkgs.firefox}/Applications/Firefox.app/Contents/MacOS/firefox";
  };

  launchd.agents.sketchybar-bottom = {
    enable = true;
    config = {
      Label = "org.nix-community.home.sketchybar-bottom";
      ProcessType = "Interactive";
      KeepAlive = true;
      RunAtLoad = true;
      StandardOutPath = "${config.home.homeDirectory}/Library/Logs/sketchybar/sketchybar-bottom.out.log";
      StandardErrorPath = "${config.home.homeDirectory}/Library/Logs/sketchybar/sketchybar-bottom.err.log";
      Program = "${sketchybarBottom}/bin/sketchybar-bottom";
    };
  };

  services.jankyborders = {
    enable = true;
    settings = {
      width = 5.0;
      active_color = osConfig.palette.CYAN;
      inactive_color = osConfig.palette.OVERLAY;
      hidpi = "on";
    };
  };

  programs.sketchybar = {
    enable = true;
    includeSystemPath = true;
    extraPackages = [
      pkgs-unstable.yabai
      pkgs.entr
      pkgs.ifstat-legacy
      pkgs.jq
      pkgs.jankyborders
    ];
  };

  programs.git = {
    settings = {
      user = {
        email = "andy.bolton@smartwyre.com";
      };
    };
  };
}
