{
  config,
  lib,
  pkgs,
  pkgs-unstable,
  osConfig,
  ...
}:
let
  sketchybarBottom = pkgs.callPackage ../pkgs/sketchybar-bottom.nix { inherit pkgs-unstable; };

  colorsScript = pkgs.writeShellScript "colors.sh" ''
    # Generated by Nix from the active Stylix base16 scheme. Do not edit.
    # See home-manager/colors.nix.
    ${lib.concatStringsSep "\n" (
      lib.mapAttrsToList (n: v: "export ${n}=${v}") (lib.filterAttrs (_: lib.isString) osConfig.palette)
    )}
  '';

  mkSymLink = config.lib.file.mkOutOfStoreSymlink;

  sketchybarInstances = [
    "sketchybar"
    "sketchybar-bottom"
  ];

  mkSketchybarLinks =
    instance:
    (lib.mapAttrs' (
      file: _:
      lib.nameValuePair "${instance}/${file}" {
        source = mkSymLink "${config.dotfilesPath}/sketchybar/${file}";
      }
    ) (builtins.readDir ./dotfiles/sketchybar))
    // {
      "${instance}/colors.sh".source = colorsScript;
    };

  sketchybarLinks = lib.foldl' (
    acc: instance: acc // mkSketchybarLinks instance
  ) { } sketchybarInstances;

  # Workspace farms ($root/.workspaces/<TICKET>) are owned by the nvim
  # workspaces plugin (dotfiles/nvim/lua/workspaces/). This PreToolUse hook is
  # the entire Claude integration: before Edit/Write, run the plugin's generic
  # guard, which claims a worktree for unclaimed farm repos and no-ops
  # everywhere else. All decision logic lives in guard.lua; the bash prefilter
  # only avoids a ~130ms headless-nvim spawn on edits outside the farm root.
  workspaceGuardHook = pkgs.writeShellScript "hm-claude-workspace-guard" ''
    input=$(cat)
    file=$(${pkgs.jq}/bin/jq -r '.tool_input.file_path // .tool_input.notebook_path // empty' <<<"$input")
    case "$file" in
      "''${WORKTREE_SOURCE_ROOT:-$HOME/smartwyre}/.workspaces/"*) ;;
      *) exit 0 ;;
    esac
    err=$(${config.programs.neovim.finalPackage}/bin/nvim -l ${config.dotfilesPath}/nvim/lua/workspaces/guard.lua "$file" 2>&1) || {
      echo "workspaces guard blocked the edit: $err" >&2
      exit 2
    }
  '';
in
{
  imports = [
    ./modules/firefox.nix
    ./options/work.nix
    ./shared.nix
  ];

  targets.darwin.copyApps.enable = true;
  targets.darwin.linkApps.enable = false;

  home.homeDirectory = "/Users/andybolton";

  xdg.configFile = sketchybarLinks // {
    "skhd/home-manager.skhdrc".source = mkSymLink "${config.dotfilesPath}/skhd/home-manager.skhdrc";
  };

  home.file.".hammerspoon/init.lua".source = mkSymLink "${config.dotfilesPath}/hammerspoon/init.lua";

  home.packages = with pkgs; [
    _1password-cli
    _1password-gui
    (azure-cli.withExtensions [
      azure-cli-extensions.azure-devops
      azure-cli-extensions.durabletask
      azure-cli-extensions.quota
      azure-cli-extensions.resource-graph
    ])
    (pkgs.writeShellScriptBin "jetkvm-kiosk" ''
      set -e

      mkdir -p "${config.home.homeDirectory}/vms"
      # --out-link roots the image against GC; the overlay's backing file lives
      # in the store, so without a root a GC would corrupt the overlay.
      nix build ${config.repoPath}#nixosConfigurations.jetkvm-kiosk.config.system.build.images.qemu-efi \
        --out-link "${config.home.homeDirectory}/vms/jetkvm-kiosk-base"
      base=$(echo "$(readlink -f "${config.home.homeDirectory}/vms/jetkvm-kiosk-base")"/*.qcow2)
      overlay="${config.home.homeDirectory}/vms/jetkvm-kiosk-overlay.qcow2"
      cur=$(${pkgs.qemu}/bin/qemu-img info --output=json "$overlay" 2>/dev/null | ${pkgs.jq}/bin/jq -r '."backing-filename" // empty')

      if [ "$cur" != "$base" ]; then
        echo "New base image, recreating overlay..."
        ${pkgs.qemu}/bin/qemu-img create -f qcow2 -F qcow2 -b "$base" "$overlay"
      fi

      exec ${pkgs.qemu}/bin/qemu-system-aarch64 \
        -machine virt \
        -accel hvf \
        -cpu host \
        -m 2G \
        -smp 2 \
        -nic user,model=virtio-net-pci \
        -drive file="$overlay",if=virtio \
        -drive if=pflash,format=raw,readonly=on,file=${pkgs.qemu}/share/qemu/edk2-aarch64-code.fd \
        -device virtio-gpu-pci \
        -display cocoa,full-screen=on,full-grab=on \
        -device qemu-xhci \
        -device usb-kbd \
        -device usb-tablet \
        "$@"
    '')
    desktoppr
    gatherv2
    jira-cli-go
    maccy
    moonlight-qt
    pngpaste
    powershell
    powershell-editor-services
    sketchybarBottom
  ];

  # Workspace hooks merged into ~/.claude/settings.json without letting nix
  # own the file, same pattern as claudeNotifyHooks in modules/claude.nix.
  home.activation.claudeWorkspaceHooks =
    lib.hm.dag.entryAfter [ "writeBoundary" ]
      # bash
      ''
        settings="$HOME/.claude/settings.json"
        ${pkgs.coreutils}/bin/mkdir -p "$HOME/.claude"
        [ -s "$settings" ] || echo '{}' > "$settings"

        new=$(${pkgs.jq}/bin/jq --arg guard ${workspaceGuardHook} '
          .hooks.PreToolUse |= [ { matcher: "Edit|Write|MultiEdit|NotebookEdit", hooks: [ { type: "command", command: $guard } ] } ]
          | .skillOverrides."worktree-session" = "off"
          | .claudeMdExcludes = (((.claudeMdExcludes // []) + ["**/infra-orchestrator/.claude/skills/worktree-session/SKILL.md"]) | unique)
        ' "$settings" 2>/dev/null) || {
          echo "claude-code: settings.json is not valid JSON, skipping workspace hook patch" >&2
          new=""
        }

        if [ -n "$new" ] && [ "$new" != "$(${pkgs.coreutils}/bin/cat "$settings")" ]; then
          printf '%s\n' "$new" > "$settings"
        fi
      '';

  # Project context for ~/smartwyre (loaded by all work sessions, farm or root).
  home.file."smartwyre/CLAUDE.md" = {
    force = false;
    text = ''
      On a new session, name it after the workspace ticket (the workspace CLAUDE.md states it). If there is no workspace ticket, ask for the CLOUD number and name the session after it; if there is none, name it after the question.

      On a new session, always descend into infra-orchestrator and load any skills.

      ## Layout

      - `~/smartwyre/<repo>/` — main clones (`.git` directory). Edits here are for clone maintenance only; ticket work happens in workspaces.
      - `~/smartwyre/.workspaces/<TICKET>/` — workspace farms (nvim workspaces plugin): one entry per repo, a symlink to the main clone until claimed, then a git worktree in place. Ticket worktrees always live here — never in ad-hoc directories. Each farm's generated CLAUDE.md documents claiming and the shell-write rule.
      - Create or sync a farm headlessly: `nvim -l ~/.config/nvim/lua/workspaces/sync.lua <TICKET>` (prints the farm path).

      ## Claude sessions

      Work sessions launch inside a workspace farm, never in the bare `~/smartwyre` root (`<leader>aw` in nvim opens claude in the farm; at the root it opens the workspace picker instead). Sessions and transcripts are bucketed per ticket; auto-memory is shared across all smartwyre work via each farm's generated `.claude/settings.json`.
    '';
  };

  programs.claude-code.mcpServers = {
    atlassian = {
      type = "sse";
      url = "https://mcp.atlassian.com/v1/sse";
    };

    azure = {
      type = "stdio";
      command = "npx";
      args = [
        "-y"
        "@azure/mcp@latest"
        "server"
        "start"
      ];
    };

    azure-devops = {
      type = "stdio";
      command = "npx";
      args = [
        "-y"
        "@azure-devops/mcp"
        "smartwyre"
      ];
    };

    terraform = {
      type = "stdio";
      command = "npx";
      args = [
        "-y"
        "terraform-mcp-server"
      ];
    };
  };

  home.sessionPath = [
    "${config.home.homeDirectory}/Applications/Home Manager Apps/WezTerm.app"
  ];

  home.sessionVariables = {
    BROWSER = "${pkgs.firefox}/Applications/Firefox.app/Contents/MacOS/firefox";
  };

  launchd.agents.sketchybar-bottom = {
    enable = true;
    config = {
      Label = "org.nix-community.home.sketchybar-bottom";
      ProcessType = "Interactive";
      KeepAlive = true;
      RunAtLoad = true;
      StandardOutPath = "${config.home.homeDirectory}/Library/Logs/sketchybar/sketchybar-bottom.out.log";
      StandardErrorPath = "${config.home.homeDirectory}/Library/Logs/sketchybar/sketchybar-bottom.err.log";
      Program = "${sketchybarBottom}/bin/sketchybar-bottom";
    };
  };

  services.jankyborders = {
    enable = true;
    settings = {
      width = 5.0;
      active_color = osConfig.palette.CYAN;
      inactive_color = osConfig.palette.OVERLAY;
      hidpi = "on";
    };
  };

  programs.sketchybar = {
    enable = true;
    includeSystemPath = true;
    extraPackages = [
      pkgs-unstable.yabai
      pkgs.entr
      pkgs.ifstat-legacy
      pkgs.jq
      pkgs.jankyborders
    ];
  };

  programs.git = {
    settings = {
      user = {
        email = "andy.bolton@smartwyre.com";
      };
    };
  };
}
